Repository googleapis/python-grafeas, pull requests merged in 2022-04, with the labels that each got.

#159 chore: allow releases on previous major versions
  .github/release-please.yml
  owlbot.py
Labels: api: containeranalysis, size: xs

#153 chore: set up CI on v0 branch
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  noxfile.py
Labels: api: containeranalysis, size: m

#162 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v0 release
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/conf.py
  grafeas/grafeas_v1/gapic/grafeas_client.py
  grafeas/grafeas_v1/gapic/transports/grafeas_grpc_transport.py
  grafeas/grafeas_v1/proto/attestation_pb2.py
  grafeas/grafeas_v1/proto/build_pb2.py
  grafeas/grafeas_v1/proto/deployment_pb2.py
  grafeas/grafeas_v1/proto/grafeas_pb2.py
  grafeas/grafeas_v1/proto/grafeas_pb2_grpc.py
  grafeas/grafeas_v1/proto/package_pb2.py
  grafeas/grafeas_v1/proto/provenance_pb2.py
  grafeas/grafeas_v1/proto/upgrade_pb2.py
  grafeas/grafeas_v1/proto/vulnerability_pb2.py
  noxfile.py
  setup.py
Labels: api: containeranalysis, size: l
